### ISSUE TITLE
Potential Dataset Version Mismatch

### ISSUE THREAD

**Issue by ItsThanhTung** [Chrixtar/latentsplat#1]
It appears that there's a discrepancy between the dataset version mentioned in the paper and the dataset actually utilized by the repository. Currently, the repository is likely operating on CO3Dv1, while it should be using CO3Dv2. Please correct me if I'm mistaken.

**Comment by Chrixtar** [comment]
Hi,

thank you very much for pointing this out.
You are correct, we have unfortunately mistaken CO3Dv1 with v2.
However, note that we still trained and evaluated all models and baselines on the same data.
We will correct this mistake in the paper and potentially run all experiments again on v2.

Best
Chris
