### ISSUE TITLE
high dimensional features rasterization

### ISSUE THREAD

**Issue by Zhirui86** [Chrixtar/latentsplat#4]
Hi! Thanks for your great contribution! I'm currently trying to splat high-dimensional features (like 512) following  your [https://github.com/Chrixtar/latent-gaussian-rasterization](url), however the PCA visual result is far from desirable.Could you plz provide more details concerning your high-dimensional splatting? Does it support dimension like 512 or more? Thanks in advance.
Desirable:
![image](https://github.com/Chrixtar/latentsplat/assets/123065672/d2a7e00f-ad5f-453b-a4cf-76f1338c76e3)
Result:
![image](https://github.com/Chrixtar/latentsplat/assets/123065672/1df1b6ca-253e-4466-8593-c436402c2e4b)

**Comment by Chrixtar** [comment]
Hi Zhirui86,

thank you very much for your interest in our work.
I have not tried that large feature dimensionalities, but the latent gaussian rasterizer should work, as long as it fits into memory.
From the given information it is hard to tell the problem. 
How exactly were these two renderings obtained? 
I could help you the most, if you could provide code/data (references) such that I would be able to reproduce your results.
If that is not possible, then we can also try a detailed description of your approach :)

Best
Chris

**Comment by Zhirui86** [comment]
@Chrixtar Thanks for your attention, Chris! Let me explain my approach in a more detailed way:

1. In order to render high-dimensional features, I firstly modified `#define NUM_FEATURE_CHANNELS 4 // 64` into `#define NUM_FEATURE_CHANNELS 512 ` in `latent-gaussian-rasterization/cuda_rasterizer/config.h` and ran `pip install latent-gaussian-rasterization` to rebuild and reinstall.
To test the effectiveness of rendered high-dimensional features, I followed steps shown as follows:
2. Use pre-trained ViT-L to generate pixel-wise 512-dimension features from source views which contain semantic information and visualize one of them via PCA which has been displayed as `desirable` in my last comment.
3. Then I concatenated features of different views and unprojected them into gaussians like:
```python
gaussians = Gaussians(rearrange(
                means,
                "b v r srf spp xyz -> b (v r srf spp) xyz",
            ),
            rearrange(
                covariances,
                "b v r srf spp i j -> b (v r srf spp) i j",
            ),
            rearrange(
                harmonics,
                "b v r srf spp c d_sh -> b (v r srf spp) c d_sh",
            ),
            rearrange(
                opacities,
                "b v r srf spp -> b (v r srf spp)",
            ),
            rearrange(
                lang_features,
                "b v r srf spp d -> b (v r srf spp) d",
            ),
        )
``` 
4.Finally, I rendered feature map following latent-gaussian-rasterization:
```python
image, feature , _, _, radii = rasterizer(
            means3D=gaussian_means[i],
            means2D=mean_gradients,
            shs=shs[i] if use_sh else None,
            colors_precomp=None if use_sh else shs[i, :, 0, :],
            features=gaussian_lang_features[i],
            opacities=gaussian_opacities[i, ..., None],
            cov3D_precomp=gaussian_covariances[i, :, row, col],
        )
``` 
However, the visual result of rendered high dimensional features is far from which has been obtained by ViT-L directly. That is, the gap between `desirable` and `result`. It's reasonable that source features and rendered features share much the same information which confuses me with the actual result. It would be greatly appreciated if you could offer me some suggestions on unprojecting and rendering features or potential causes. Many Thanks!
