### ISSUE TITLE
Question about gaussians's ply

### ISSUE THREAD

**Issue by kevinchiu19** [Chrixtar/latentsplat#5]
Hi! Thanks for your great contribution!
I exported the ply file through the code provided and found that all the scenes are basically like this, as shown in the figure:
![image](https://github.com/Chrixtar/latentsplat/assets/52447673/3d2bbc33-3495-4216-9055-8be62a86e024)

Does this ply represent any physical meaning?

**Comment by Chrixtar** [comment]
Hi,

thanks for your interest in our work.
If I am not mistaken, you just visualize all Gaussian means here irrespective of their scales and opacity. Especially the opacity is important to ignore Gaussians that do not contribute significantly.
If you look at depth renderings instead, they look more reasonable and are easier to interpret, as all structural parameters of the Gaussians are accounted for.

Feel free to reopen the issue in case of follow-up questions :)

Best
Chris
