### ISSUE TITLE
how can I train on re10k?

### ISSUE THREAD

**Issue by BroenLin** [Chrixtar/latentsplat#6]
Is there a corresponding command?

**Comment by Chrixtar** [comment]
Hi BroenLin,

the explanations in the [Readme](https://github.com/Chrixtar/latentsplat#training) just use ```co3d_hydrant``` as an example.
The command for training on re10k is (referring to the ```config/experiment/re10k.yaml```):
```bash
python3 -m src.main +experiment=re10k
```
For evaluation of extrapolation on re10k, the command would be:
```bash
python3 -m src.main +experiment=re10k mode=test dataset/view_sampler=evaluation dataset.view_sampler.index_path=assets/evaluation_index/re10k_extra.json checkpointing.load=checkpoints/re10k.ckpt
```
I recommend checking out the [hydra documentation](https://hydra.cc/docs/1.3/intro/), as we use it for our experiment configurations.

Best
Chris
